config/routes.rb
Rails.application.routes.draw do

  #mount LetterOpenerWeb::Engine, at: "/letter_opener"

  root "tests#index"

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout},
             controllers: { registrations: 'users/registrations' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  # GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  namespace :admin do
    root 'tests#index'
    resources :tests do
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
  #resources :categories
  #resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  after_validation :after_validation_set_next_question, on: :update

  SUCCESS_PERCENT = 85

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end
    save!
  end

  def success?
    percents >= SUCCESS_PERCENT
  end

  def percents
    self.correct_questions * 100 / questions_count
  end

  def question_number
    questions_count - remained_questions.count
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def after_validation_set_next_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def questions_count
    test.questions.count
  end

  def remained_questions
    test.questions.order(:id).where('id > ?', current_question.id)
  end

  def next_question
    remained_questions.first
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result]

  def show

  end

  def result

  end

  def update
    @test_passage.accept!(params[:answer_ids])
    if @test_passage.completed?
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def test_result(test_passage)
    if test_passage.success?
      "<p class=\"result--success\">You Passed! Your result: #{test_passage.percents}%</p>".html_safe
    else
      "<p class=\"result--fail\">You Failed! Your result: #{test_passage.percents}%</p>".html_safe
    end
  end
end

app/views/test_passages/result.html.erb
<h1>The <%= @test_passage.test.title %> Test was Completed!</h1>
<p>
  <%= test_result(@test_passage) %>
</p>

<p>
  <%= link_to 'All tests', tests_path %>
</p>

app/views/test_passages/show.html.erb
<h1>Passing the <%= @test_passage.test.title %> </h1>

<p>
  Question <%= @test_passage.question_number %> / <%= @test_passage.test.questions.count %>
</p>

<b>
  <%= @test_passage.current_question.body %>
</b>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>

  <p><%= form.submit 'Next' %></p>
<% end %>