config/routes.rb
Rails.application.routes.draw do

  #mount LetterOpenerWeb::Engine, at: "/letter_opener"

  root "tests#index"

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout},
             controllers: { registrations: 'users/registrations' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  # GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  namespace :admin do
    root 'tests#index'
    resources :tests do
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
  #resources :categories
  #resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController

  before_action :find_question, only: %i[show destroy edit update]
  before_action :find_test, only: %i[index create new]
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def index
    @questions = @test.questions
  end

  def show
  end

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to admin_test_path(@test)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit
    end
  end

  #Удаление вопроса
  def destroy
    @question.destroy
    redirect_to @question.test
  end

  private

  def question_params
    params.require(:question).permit(:body)
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def rescue_with_question_not_found
    render plain: 'Question was not found'
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(resource)
    if resource.persisted?
      "Edit #{resource.test.title} Question"
    else
      "Create New #{resource.test.title} Question"
    end
  end
end

app/views/admin/questions/_form.html.erb
<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <%= render 'shared/errors', resource: @question %>
  <p>
    <%= form.label :body %>
    <%= form.text_field :body %>
  </p>
  <p><%= form.submit %></p>
<% end %>

app/views/admin/questions/_question.erb
<tr>
  <td><%= question.body %></td>
  <td><%= question.test_id %></td>
  <td><%= question.answers.count %>
  <td><%= link_to 'Show', admin_question_path(question) %></td>
  <td><%= link_to 'Edit', edit_admin_question_path(question) %></td>

  <td>
    <%= link_to 'Delete',
                admin_question_path(question),
                method: :delete,
                data: {confirm: 'Are you sure?'} %>
  </td>
</tr>

app/views/admin/questions/edit.html.erb
<h1><%= question_header(@question) %></h1>
<br/>

<%= render 'form' %>

<%= link_to 'Back', admin_test_path(@question.test) %>

app/views/admin/questions/index.html.erb
<h1>Show Questions</h1>

<p>
  <%= link_to 'New question', new_admin_question_path(@test) %>
</p>

<table>
  <tr>
    <th>Body</th>
    <th>Test Id</th>
    <th>Answers count</th>
    <th colspan="3">Actions</th>
  </tr>

  <%= render @questions %>
</table>

app/views/admin/questions/new.html.erb
<h1><%= question_header(@question) %></h1>
<br/>

<%= render 'form' %>

<%= link_to 'Back', admin_test_path(@test) %>

app/views/admin/questions/show.html.erb
<h1><%= @question.body %></h1>

<h2>Answers</h2>

<%= link_to 'New answer', new_admin_question_answer_path(@question)  %>

<ol>
  <%= render @question.answers %>
</ol>

<% @question.answers.each do |answer| %>
  <p><%= answer.body %></p>
  <p>Correct: <%= answer.correct %></p>
<% end %>

<p><%= link_to 'Edit', edit_admin_question_path(@question) %></p>
<p><%= link_to 'Delete', admin_question_path(@question), method: :delete, data: {confirm: "Are you sure?" } %></p>
<p><%= link_to 'Back', admin_test_path(@question.test) %></p>